services:
  app:
    container_name: nest-app
    image: my-nest-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - '1337:1337'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
